### DISCUSSION TITLE
Strange disconnection from HA

### DISCUSSION THREAD

**Discussion by Absolonj** [fsaris/EspHome-AwoX-BLE-mesh-hub#110] [Q&A]
I installed the AwoX MESH HUB with the help of ESPHome according to the instructions and everything worked perfectly including the controls in HA. Then after some time the device disconnected and its status remained N/A. After a few attempts everything started again and after some time it disconnected again. Now the device is still unavailable.

According to the log from ESPHome everything seems to be fine:

```
[22:37:23][D][awox.mesh:236]: Total devices: 1
[22:37:23][D][awox.mesh:239]: Available device A4:C1:38:68:39:51 [14673] => rssi: -82
[22:37:23][D][awox.mesh:264]: Currently 1 mesh devices reachable through active connections (1 currently known and 1 fully recognized)
[22:37:23][D][awox.mesh:133]: No devices found to connect to
``` 

The endless loop runs over and over again, scanning the only device I have connected.

The device also connects correctly to MQTT, see log:

```
1731362852: New connection from 192.168.88.82:55507 on port 1883.
1731362852: New client connected from 192.168.88.82:55507 as awox-ble-mesh-hub-142b2f9f6574 (p2, c0, k15).
``` 

But nothing will happen. The device keeps refreshing the awox-ble-mesh-hub/debug topik in mqqt, but in HA the mesh-hub and the device appear unavailable.

Here is my config script:

```
substitutions:
  name: awox-ble-mesh-hub
  friendly_name: "AwoX BLE mesh hub"

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  min_version: 2024.6.0
  name_add_mac_suffix: false

esp32:
  board: esp32dev
  framework:
    type: esp-idf

#status_led:
#  pin: GPIO2

logger:
  # level: VERY_VERBOSE

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_password
  discovery_retain: True  # Zabrání uložení MQTT zpráv

ota:
  platform: esphome
  #password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: "awox-ble-mesh-hub"

external_components:
  - source:
      type: git
      url: https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub
      ref: main

esp32_ble_tracker:
  scan_parameters:
    active: false  # Pasivní BLE skenování, šetří energii

awox_mesh:
  mesh_name: !secret mesh_name
  mesh_password: !secret mesh_password

  device_info:
    - product_id: 0x26
      device_type: RGB
      manufacturer: EGLO
      name: EGLOPanel 60X60
      model: EPanel_600
      icon: mdi:led-outline
```
