### DISCUSSION TITLE
Clarification on device_info

### DISCUSSION THREAD

**Discussion by TheAndi** [fsaris/EspHome-AwoX-BLE-mesh-hub#115] [Q&A]
Just a short question about the `device_info` section.

If I have multiple lamps of the same model, do I need to put the entry multiple times?
Like this?

```
  device_info:
    # Example device type, see device info in HomeAssistant or MQTT message to find the 'product_id'
  - product_id: 0x96
    device_type: RGB
    name: EGLO RGB+TW
    model: EGLO-RGB-TW
    manufacturer: EGLO
  - product_id: 0x96
    device_type: RGB
    name: EGLO RGB+TW
    model: EGLO-RGB-TW
    manufacturer: EGLO
```

If yes, what's the purpose of the name tag?
It would make sense to me to appropriately name the lamps like "bathroom", "kitchen", ... but how would the component know which lamps are which? Is there a way to specify the `mesh-id` or the `mac-adress` of the lamp in the `device_info`. Then it would make sense to me.

Thanks for clarifying!
