### DISCUSSION TITLE
How could I control the mesh from the ESP?

### DISCUSSION THREAD

**Discussion by mverburg** [fsaris/EspHome-AwoX-BLE-mesh-hub#78] [Q&A]
Hi,

First of all thanks for this great project. I've recently been able to set it up on a [shelly-plus-1 ](https://devices.esphome.io/devices/Shelly-Plus-1) relay.

The idea I have is to use the shelly in detached mode. 

So if the device is connected to the mesh, toggling the wall switch will trigger a state change of the light directly via  the mesh. But if (for whatever reason) the connection to the mesh is unavailable, use the relais to switch the power.

Right now I'm experimenting with sending a `mqtt` message when the wall switch is used but that seems overly complex.

Right now I'm toying around with something like this:

```yaml
binary_sensor:
  - platform: gpio
    name: "${device_name} Switch"
    pin: GPIO4
    on_state:
      then:
        - if:
            condition:
              and:
                - wifi.connected:
                - mqtt.connected:
            then:
              - mqtt.publish_json:  # not sure this even works yet
                  topic: shelly-plus-1-schakelaar-1/group-32768/command
                  payload: |-
                    root["state"] = "ON";
            else:
              - switch.toggle: relay
    # on_state:
    #   then:
    #     - switch.toggle: "relay"
    filters:
      - delayed_on_off: 50ms
```

In an ideal world I'd like to be able to check if the connection with the mesh is up and then send a message to the correct group (or device) directly.

That way I would loose the wifi and mqtt dependency when toggling the light.

Is that even possible or should I continue down the path I'm on?
