### ISSUE TITLE
Issues with adding a EGLO Salobrena-C BLE lamp

### ISSUE THREAD

**Issue by Dev-Sniper** [fsaris/EspHome-AwoX-BLE-mesh-hub#121]
I have a couple of EGLO Salobrena-C lamps from 2021 that can be connected to the Awox Smart Control / Awox Home Control App via BLE. The firmware on them is up to date (Version 2.6.17) and they can be reset and reconnected to the official Apps. I´ve talked to EGLOs customer support so I know that these lamps have BLE connectivity but can´t be controlled by a zigbee hub. When resetting the lamps they show up with the name "unpaired" on Android phones (but not on iPhones and a bluetooth dongle I tried to use didn´t get them either). Thus I´ve switched to a regular ESP-32 (ESP32-WROOM32D) that I flashed with the ESPHome "Bluetooth proxy" prebuilt image. That works and the device can be found in the ESPHome Dashboard of my Homeassistant instance. Then I went through the [instructions](https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/discussions/71#discussion-6234371).

Step 1: the ESP can be flashed and connects to the wireless network

Step 2: adding the logger works (although I don´t have the "Logs" -> "wireless" option, but the log button on the added device shows the logs wether it´s connected via wifi or usb)

the output is:

```INFO ESPHome 2025.2.1

INFO Reading configuration /config/esphome/awox-ble-mesh-hub.yaml...

INFO Starting log output from [IP] using esphome API

INFO Successfully connected to awox-ble-mesh-hub @ [IP] in 0.100s

INFO Successful handshake with awox-ble-mesh-hub @ [IP] in 0.151s

[I][app:100]: ESPHome version 2025.2.1 compiled on [Date & time]

[C][wifi:600]: WiFi:

[C][wifi:428]:   Local MAC: [MAC]

[C][wifi:433]:   SSID: [SSID]

[C][wifi:436]:   IP Address: [IP]

[C][wifi:439]:   BSSID: [BSSID]

[C][wifi:441]:   Hostname: 'awox-ble-mesh-hub'

[C][wifi:443]:   Signal strength: -56 dB ▂▄▆█

[V][wifi:445]:   Priority: 0.0

[C][wifi:447]:   Channel: 1

[C][wifi:448]:   Subnet: [Subnet]

[C][wifi:449]:   Gateway: [Gateway]

[C][wifi:450]:   DNS1: [DNS]

[C][wifi:451]:   DNS2: [DNS]

[C][logger:177]: Logger:

[C][logger:178]:   Max Level: VERY_VERBOSE

[C][logger:179]:   Initial Level: VERY_VERBOSE

[C][logger:181]:   Log Baud Rate: 115200

[C][logger:182]:   Hardware UART: UART0

[C][mdns:116]: mDNS:

[C][mdns:117]:   Hostname: awox-ble-mesh-hub

[V][mdns:118]:   Services:

[V][mdns:120]:   - _esphomelib, _tcp, 6053

[V][mdns:122]:     TXT: friendly_name = awox-ble-mesh-hub

[V][mdns:122]:     TXT: version = 2025.2.1

[V][mdns:122]:     TXT: mac = [mac]

[V][mdns:122]:     TXT: platform = ESP32

[V][mdns:122]:     TXT: board = esp32dev

[V][mdns:122]:     TXT: network = wifi

[V][mdns:122]:     TXT: api_encryption = [api_encryption]

[C][esphome.ota:073]: Over-The-Air updates:

[C][esphome.ota:074]:   Address: awox-ble-mesh-hub.local:3232

[C][esphome.ota:075]:   Version: 2

[C][esphome.ota:078]:   Password configured

[C][safe_mode:018]: Safe Mode:

[C][safe_mode:019]:   Boot considered successful after 60 seconds

[C][safe_mode:021]:   Invoke after 10 boot attempts

[C][safe_mode:022]:   Remain in safe mode for 300 seconds

[C][api:140]: API Server:

[C][api:141]:   Address: awox-ble-mesh-hub.local:6053

[C][api:143]:   Using noise encryption: YES

[VV][scheduler:225]: Running interval '' with interval=60000 last_execution=160620 (now=220621)
```

Step 3: Skipped because I already set the framework type to "esp-idf" during Step 1

Step 4 & 5: Setting up the MQTT worker... this might or might not be the issue. I have created a MQTT Broker instance using the HomeAssistant Mosquitto Add-on. I´ve added the credentials for this broker to to config file and removed the homeassistant api parts. I then flashed the new config to the ESP32 and got this log:

```
INFO ESPHome 2025.2.1

INFO Reading configuration /config/esphome/awox-ble-mesh-hub.yaml...

INFO Starting log output from awox-ble-mesh-hub/debug

INFO Connected to MQTT broker!
```

So I don´t get information on the WiFi network anymore but I did get information regarding MQTT.
I haven´t used MQTT before so that´s not my area of expertise but I have published a message through the MQTT broker instance to the topic "awox-ble-mesh-hub/debug" and it did show up in the logs for my device so I would assume that MQTT and the wireless connection both work. Just for fun I published a message to "awox-ble-mesh-hub/test" and that didn´t get picked up by the device but by the MQTT broker that I previously configured to subscribe to "awox-ble-mesh-hub/#" so in theory I should see every MQTT message within my MQTT broker instance even if my device isn´t subscribed to a topic.

Step 6: I removed the captive portal part and copied the external_components section from the example YAML file. Then I installed the config on the ESP and got the same results as in Step 5. Tested the MQTT broker again, everything seems to work. I then reset one of the lamps. It showed up as unpaired on an android phone but neither my MQTT broker (which is still subscribed to "/#" nor my device logs changed. I also turned on two of the lamps within the mesh but that didn´t lead to any results either. So I´m not really sure if my devices are just incompatible with the add-on or if I messed up anything. 

Here is the final YAML configuration file that´s on my ESP right now:
```yaml
esphome:
  name: awox-ble-mesh-hub
  friendly_name: awox-ble-mesh-hub

esp32:
  board: esp32dev
  framework:
    type: esp-idf

# Enable logging
logger:
  level: VERY_VERBOSE

mqtt:
  broker: [broker name]
  username: [user name]
  password: [user password]

  # Disable retained discovery messages until you are got the config correct
  discovery_retain: True
  
ota:
  - platform: esphome
    password: [ota password]

wifi:
  ssid: [ssid]
  password: [password]

external_components:
  - source:
      type: git
      url: https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub
      ref: main
  #  ref: dev
  # - source:
  #     type: local
  #     path: components

esp32_ble_tracker:
  scan_parameters:
    active: false {I have tried setting this to true just in case it might change anything but the results were the same}

awox_mesh:
  mesh_name: [mesh name retrieved via the form linked in the github repo]
  mesh_password: [password retrieved via the form linked in the github repo]
```

Before every build I run "Clean MQTT" and "Clean Build Files" within ESP Home and check that the configuration is valid. iBeacon managed to find devices that have a name starting with the mesh name but it can´t do anything with the added devices (name schema is "[mesh name] [4 digit ID with alphanumerical characters]" example: awoxMesh D18F
