### ISSUE TITLE
Compatible with bluetooth proxy?

### ISSUE THREAD

**Issue by racinmat** [fsaris/EspHome-AwoX-BLE-mesh-hub#122]
Hi, is this component compatible with bluetooth proxy, or do I need to use a separate HW for a bluetooth proxy?
I noticed there is
```
esp32_ble_tracker:
  scan_parameters:
    active: false
```
in https://github.com/fsaris/EspHome-AwoX-BLE-mesh-hub/blob/main/awox-ble-mesh-hub.yaml#L64-L66
but 
```
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true
```
in https://esphome.io/components/bluetooth_proxy.html so I guess they are not compatible?

On the other hand I looked at https://esphome.io/components/esp32_ble_tracker.html#configuration-variables and it seems the `esp32_ble_tracker.scan_parameters.active: true` is not needed for all devices, just for some of them.
