### ISSUE TITLE
Compiling of ESPHome fails with 3 errors

### ISSUE THREAD

**Issue by dabepp** [fsaris/EspHome-AwoX-BLE-mesh-hub#31]
This is my ESPHome File:
```
 esp32:
  board: wemos_d1_mini32
substitutions:
  name: esp32-bluetooth-proxy-35ba64
packages:
  esphome.bluetooth-proxy: github://esphome/bluetooth-proxies/esp32-generic.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  compile_process_limit: 2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

bluetooth_proxy:
  active: true

mqtt:
  broker: !secret mqtt_host
  username: !secret mqtt_user
  password: !secret mqtt_password
  
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms
    active: true

api:
  encryption:
    key: "<redacted>"


logger:
  level: debug
  


external_components:
  source: github://fsaris/EspHome-AwoX-BLE-mesh-hub

awox_mesh:
  mesh_name: !secret mesh_name
  mesh_password: !secret mesh_password
  address_prefix: A4:C1:38:74:7C:A7
  device_info:
    # Example device type, see device info in HomeAssistant or MQTT message to find the 'product_id'
    - product_id: 0x30
      device_type: RGB
      manufacturer: EGLO
      name: EGLOPanel 30X120
      model: EPanel_120
      icon: mdi:wall-sconce-flat
```

This is the error:

```
HARDWARE:` ESP32 240MHz, 320KB RAM, 4MB Flash
 - framework-espidf @ 3.40405.230623 (4.4.5) 
 - tool-cmake @ 3.16.9 
 - tool-ninja @ 1.10.2 
 - toolchain-esp32ulp @ 2.35.0-20220830 
 - toolchain-xtensa-esp32 @ 8.4.0+2021r2-patch5
Reading CMake configuration...
Dependency Graph
|-- noise-c @ 0.1.4
|-- ArduinoJson @ 6.18.5
|-- Improv @ 1.2.3
Compiling /data/esp32-bluetooth-proxy-35ba64/.pioenvs/esp32-bluetooth-proxy-35ba64/src/esphome/components/awox_mesh/awox_mesh.o
Compiling /data/esp32-bluetooth-proxy-35ba64/.pioenvs/esp32-bluetooth-proxy-35ba64/src/esphome/components/awox_mesh/mesh_device.o
src/esphome/components/awox_mesh/awox_mesh.cpp:1:9: warning: #pragma once in main file
 #pragma once
         ^~~~
In file included from src/esphome/components/awox_mesh/awox_mesh.cpp:7:
src/esphome/components/awox_mesh/awox_mesh.h:8:10: fatal error: AES.h: No such file or directory

*************************************************************
* Looking for AES.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:AES.h"
* Web  > https://registry.platformio.org/search?q=header:AES.h
*
*************************************************************

 #include <AES.h>
          ^~~~~~~
compilation terminated.
*** [/data/esp32-bluetooth-proxy-35ba64/.pioenvs/esp32-bluetooth-proxy-35ba64/src/esphome/components/awox_mesh/awox_mesh.o] Error 1
src/esphome/components/awox_mesh/mesh_device.cpp:8:10: fatal error: AES.h: No such file or directory

*************************************************************
* Looking for AES.h dependency? Check our library registry!
*
* CLI  > platformio lib search "header:AES.h"
* Web  > https://registry.platformio.org/search?q=header:AES.h
*
*************************************************************

 #include <AES.h>
          ^~~~~~~
compilation terminated.
*** [/data/esp32-bluetooth-proxy-35ba64/.pioenvs/esp32-bluetooth-proxy-35ba64/src/esphome/components/awox_mesh/mesh_device.o] Error 1
========================= [FAILED] Took 22.44 seconds =========================
```

What can I do?
