### ISSUE TITLE
feature request: manually set the mac address of the light

### ISSUE THREAD

**Issue by ahpohl** [fsaris/EspHome-AwoX-BLE-mesh-hub#8]
Hi,

I finally had the time to try your new awox component with my Eglo lights. It's working great so far, but I have a feature request to make. It turns out the Eglo lights have the same mac address prefix as my Xiaomi Temp and Humidity sensors. The mac of both device classes start with `A4:C1:38`. I get initially lot's of connection failures until the device list reaches a light:

```
[19:48:49][D][mesh_device:142]: [0] [A4:C1:38:8D:D3:19] ESP_GATTC_DISCONNECT_EVT, reason 0
[19:48:49][W][esp32_ble_client:134]: [0] [A4:C1:38:8D:D3:19] Connection failed, status=133
```
[A4:C1:38:8D:D3:19]  -> xiaomi_lywsd03mmc (Temp Humidity Sensor)

Hence I would like to be able to turn automatic device discovery off once I figured out the mac address of a nearby light and manually specify a light in the config file.

```
light:
  - platform: awox_mesh
  - mesh_name: !secret mesh_name
  - mesh_password: !secret mesh_password
  - name: "Light TV-Room"
  - mac_address: A4:C1:38:9A:33:4E    <---- Eglo EFueva_225s ceiling light
  - auto_discovery: off
```

Why not integrate this component with the already existing light component as a new platform?
