### ISSUE TITLE
Add new device

### ISSUE THREAD

**Issue by oxigen-dev** [fsaris/EspHome-AwoX-BLE-mesh-hub#9]
Hi @fsaris ,

Unfortunately 3 of my devices were not recognized, could you please add them? I've pasted the MQTT payloads. For all of the lamps one can set the brightness, color, temperature. In case you need any additional information, please let me know. Thanks!

```
schema: json
name: Unknown device type
unique_id: awox-XX:XX:XX:XX:XX:XX-light
icon: mdi:lightbulb-help-outline
state_topic: awox-ble-mesh-hub/22980/state
command_topic: awox-ble-mesh-hub/22980/command
availability:
  - topic: awox-ble-mesh-hub/22980/availability
  - topic: awox-ble-mesh-hub/status
availability_mode: all
color_mode: true
brightness: true
brightness_scale: 255
supported_color_modes:
  - brightness
device:
  identifiers:
    - esp-awox-mesh-22980
    - XX:XX:XX:XX:XX:XX
  name: Unknown device type
  model: t
  manufacturer: AwoX
  via_device: ------
platform: mqtt
```

```
schema: json
name: Unknown device type
unique_id: awox-YY:YY:YY:YY:YY:YY-light
icon: mdi:lightbulb-help-outline
state_topic: awox-ble-mesh-hub/3590/state
command_topic: awox-ble-mesh-hub/3590/command
availability:
  - topic: awox-ble-mesh-hub/3590/availability
  - topic: awox-ble-mesh-hub/status
availability_mode: all
color_mode: true
brightness: true
brightness_scale: 255
supported_color_modes:
  - brightness
device:
  identifiers:
    - esp-awox-mesh-3590
    - YY:YY:YY:YY:YY:YY
  name: Unknown device type
  model: t
  manufacturer: AwoX
  via_device: -----------
platform: mqtt
```

```
schema: json
name: Unknown device type
unique_id: awox-ZZ:ZZ:ZZ:ZZ:ZZ:ZZ-light
icon: mdi:lightbulb-help-outline
state_topic: awox-ble-mesh-hub/23338/state
command_topic: awox-ble-mesh-hub/23338/command
availability:
  - topic: awox-ble-mesh-hub/23338/availability
  - topic: awox-ble-mesh-hub/status
availability_mode: all
color_mode: true
brightness: true
brightness_scale: 255
supported_color_modes:
  - brightness
device:
  identifiers:
    - esp-awox-mesh-23338
    - ZZ:ZZ:ZZ:ZZ:ZZ:ZZ
  name: Unknown device type
  model: t
  manufacturer: AwoX
  via_device: -------
platform: mqtt
```

**Comment by fsaris** [comment]
Looks like some info is missing in the message you posted.

The model value should show a product id.

It should also be visible in the UI on the device details screen

**Comment by oxigen-dev** [comment]
> Looks like some info is missing in the message you posted.
> 
> The model value should show a product id.
> 
> It should also be visible in the UI on the device details screen

@fsaris  Ooops I only have this...

![image](https://user-images.githubusercontent.com/124933927/235128987-3ecc2d59-1602-4756-aa9c-4af7f7c29d71.png)

Any ideas? :)

**Comment by MineTech13** [comment]
Have the same Issue my EPanel 600 (HW1.0) FW2.2.6 is also just registering by the model "t"

**Comment by voxain** [comment]
Same thing here. Got some of the Fueva-C models

**Comment by fsaris** [comment]
Can you check the log in ESPHome en look for productID

**Comment by voxain** [comment]
I somehow can't get this to log anymore, but the product ID was 0x40 - It's a square Fueva-C / EGLO Surface. Below I have attached the MQTT discovery log if that is helpful (Replaced the MAC Address just to be safe).
```yaml
schema: json
name: Unknown device type
unique_id: awox-A4:C1:38:XX:XX:XX-light
icon: mdi:lightbulb-help-outline
state_topic: esphome-web-305a2c/19134/state
command_topic: esphome-web-305a2c/19134/command
availability:
  - topic: esphome-web-305a2c/19134/availability
  - topic: esphome-web-305a2c/status
availability_mode: all
color_mode: true
brightness: true
brightness_scale: 255
supported_color_modes:
  - brightness
device:
  identifiers:
    - esp-awox-mesh-19134
    - A4:C1:38:XX:XX:XX
  name: Unknown device type
  model: t
  manufacturer: AwoX
  via_device: 30c6f7305a2c
platform: mqtt
```
